---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
  roles:
    - role: geerlingguy.java
    - role: cloud_labs.elasticsearch_cluster
      vars:
        elasticsearch_elastic_password: elastic_password
        elasticsearch_kibana_system_password: kibana_system_password
        elasticsearch_logstash_system_password: logstash_system_password
        elasticsearch_beats_system_password: beats_system_password
        elasticsearch_apm_system_password: apm_system_password
        elasticsearch_remote_monitoring_user_password: remote_monitoring_user_password

