---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check ports
      ansible.builtin.wait_for:
        port: "{{ item }}"
      loop:
        - 9200
        - 9300

    - name: check api
      ansible.builtin.uri:
        url: "http://localhost:9200/_security/user/elastic"
        user: elastic
        password: elastic_password
        status_code: 200
        return_content: yes
      register: result
      failed_when:
        - "'superuser' not in result.json.elastic.roles"
