---
- name: Converge node 1
  hosts: elasticsearch_node_1
  become: true
  roles:
    - role: geerlingguy.java
    - role: cloud_labs.elasticsearch_cluster
      vars:
        es_network_host: 0.0.0.0
        es_enable_http_ssl: true
        es_enable_transport_ssl: true
        es_ssl_certificate_authority: "molecule/three_nodes_basic_auth/test_certs/ca/ca.crt"
        es_ssl_key: "molecule/three_nodes_basic_auth/test_certs/elasticsearch_node_1/elasticsearch_node_1.key"
        es_ssl_certificate: "molecule/three_nodes_basic_auth/test_certs/elasticsearch_node_1/elasticsearch_node_1.crt"
        es_validate_certs: false
        es_config:
          cluster.name: "test-cluster"
          discovery.seed_hosts:
            - 172.18.0.2
            - 172.18.0.4
          http.host: "{{ es_network_host }}"
          http.port: 9200
          node.data: true
          node.master: false
          transport.host: "{{ es_network_host }}"
          transport.port: 9300
          bootstrap.memory_lock: false

- name: Converge node 2
  hosts: elasticsearch_node_2
  become: true
  roles:
    - role: geerlingguy.java
    - role: cloud_labs.elasticsearch_cluster
      vars:
        es_network_host: 0.0.0.0
        es_enable_http_ssl: true
        es_enable_transport_ssl: true
        es_ssl_certificate_authority: "molecule/three_nodes_basic_auth/test_certs/ca/ca.crt"
        es_ssl_key: "molecule/three_nodes_basic_auth/test_certs/elasticsearch_node_2/elasticsearch_node_2.key"
        es_ssl_certificate: "molecule/three_nodes_basic_auth/test_certs/elasticsearch_node_2/elasticsearch_node_2.crt"
        es_validate_certs: false
        es_config:
          cluster.name: "test-cluster"
          discovery.seed_hosts:
            - 172.18.0.2
            - 172.18.0.3
          http.host: "{{ es_network_host }}"
          http.port: 9200
          node.data: true
          node.master: false
          transport.host: "{{ es_network_host }}"
          transport.port: 9300
          bootstrap.memory_lock: false
          
- name: Converge
  hosts: elasticsearch_master
  become: true
  roles:
    - role: geerlingguy.java
    - role: cloud_labs.elasticsearch_cluster
      vars:
        es_elastic_password: elastic_password
        es_kibana_system_password: kibana_system_password
        es_logstash_system_password: logstash_system_password
        es_beats_system_password: beats_system_password
        es_apm_system_password: apm_system_password
        es_remote_monitoring_user_password: remote_monitoring_user_password
        es_network_host: 0.0.0.0
        es_enable_http_ssl: true
        es_enable_transport_ssl: true
        es_ssl_certificate_authority: "molecule/three_nodes_basic_auth/test_certs/ca/ca.crt"
        es_ssl_key: "molecule/three_nodes_basic_auth/test_certs/elasticsearch_master/elasticsearch_master.key"
        es_ssl_certificate: "molecule/three_nodes_basic_auth/test_certs/elasticsearch_master/elasticsearch_master.crt"
        es_validate_certs: false
        es_config:
          cluster.name: "test-cluster"
          cluster.initial_master_nodes:
            - elasticsearch_master
          discovery.seed_hosts:
            - 172.18.0.3
            - 172.18.0.4
          http.host: "{{ es_network_host }}"
          http.port: 9200
          node.data: false
          node.master: true
          transport.host: "{{ es_network_host }}"
          transport.port: 9300
          bootstrap.memory_lock: false
