- name: Create Configuration Directory
  file:
    path: "{{ es_conf_dir }}"
    state: directory
    owner: root
    group: "{{ es_group }}"
    mode: "2750"

- name: Create PID Directory
  file:
    path: "{{ es_pid_dir }}"
    state: directory
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: "0755"

- name: Create Others Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: "2750"
  loop:
    - "{{ es_log_dir }}"
    - "{{ es_data_dirs }}"

- name: Copy Configuration File
  template:
    src: elasticsearch.yml.j2
    dest: "{{ es_conf_dir }}/elasticsearch.yml"
    owner: root
    group: "{{ es_group }}"
    mode: "0660"
    force: yes
  register: system_change
  notify: restart elasticsearch

- name: Configure Elasticsearch 7+.
  template:
    src: "{{ item | basename }}.j2"
    dest: "{{ item }}"
    owner: root
    group: elasticsearch
    mode: "0660"
  loop:
    - /etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch