---

- name: Debian - Install required dependencies
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Debian - Add Elasticsearch repository key
  apt_key:
    url: '{{ es_apt_key }}'
    id: '{{ es_apt_key_id }}'
    state: present
  when: es_add_repository and es_apt_key | string

- name: Debian - Add elasticsearch repository
  apt_repository:
    repo: '{{ es_apt_url }}'
    state: 'present'

- name: Include optional user and group creation.
  when: (es_user_id is defined) and (es_group_id is defined)
  include: elasticsearch-optional-user.yml

- name: Debian - Get installed elasticsearch version
  command: dpkg-query --showformat='${Version}' --show {{ es_package_name }}
  register: installed_es_version
  failed_when: False
  changed_when: False
  check_mode: no

- name: Debian - Ensure elasticsearch is installed
  become: yes
  apt:
    name: '{{ es_package_name }}{% if es_version is defined and es_version != "" %}={{ es_version }}{% endif %}'
    state: present
    allow_unauthenticated: "{{ 'no' if es_apt_key else 'yes' }}"
    cache_valid_time: 86400
  register: debian_elasticsearch_install_from_repo
  notify: restart elasticsearch
  environment:
    ES_PATH_CONF: "{{ es_conf_dir }}"
