---
- name: Create the elasticsearch keystore
  block:
  - name: Create the keystore if it doesn't exist yet
    command: >
     {{es_home}}/bin/elasticsearch-keystore create
    args:
      creates: "{{ es_conf_dir }}/elasticsearch.keystore"

  - name: Check if bootstrap password is set
    command: >
     {{es_home}}/bin/elasticsearch-keystore list
    register: list_keystore
    changed_when: False
    check_mode: no

  - name: Create Bootstrap password for elastic user
    shell: echo {{ es_elastic_password | quote }} | {{ es_home }}/bin/elasticsearch-keystore add -x 'bootstrap.password'
    when:
      - es_elastic_password is defined and list_keystore is defined and 'bootstrap.password' not in list_keystore.stdout_lines
    no_log: true

- name: Set elasticsearch.keystore Permissions
  file:
    state: file
    path: "{{ es_conf_dir }}/elasticsearch.keystore"
    owner: root
    group: "{{ es_group }}"
    mode: "660"
