---

- set_fact: "es_major_version={{ es_version.split('.')[0] }}.x"
  when:
    - es_major_version is undefined
  tags:
    - always

- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
    - always

- name: set compatibility variables
  include: compatibility-variables.yml
  tags:
    - always

- name: check-set-parameters
  include: elasticsearch-parameters.yml
  tags:
    - always

- name: Install Elasticsearch
  include: elasticsearch-Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - install

- name: include elasticsearch-config.yml
  include: elasticsearch-config.yml
  tags:
    - config

  #We always execute xpack as we may need to remove features
- name: include xpack/elasticsearch-xpack.yml
  include: xpack/elasticsearch-xpack.yml
  tags:
    - xpack

- name: include elasticsearch-ssl.yml
  include: elasticsearch-ssl.yml
  when: es_enable_http_ssl or es_enable_transport_ssl
  tags:
    - xpack

- name: flush handlers
  meta: flush_handlers

- name: Make sure elasticsearch is started
  become: yes
  service: name=elasticsearch state=started enabled=yes
  when: es_start_service

- name: Wait for elasticsearch to startup
  wait_for: host={{ es_api_host }} port={{ es_api_port }} delay=5 connect_timeout=1
  when: es_restarted is defined and es_restarted.changed and es_start_service

- name: set fact manage_native_realm to false
  set_fact: manage_native_realm=false

- name: set fact manage_native_realm to true
  set_fact: manage_native_realm=true
  when:
    - es_start_service
    - (es_users is defined and es_users.native is defined) or (es_roles is defined and es_roles.native is defined)

# If playbook runs too fast, Native commands could fail as the Native Realm is not yet up
- name: Wait {{ es_api_sleep }} seconds for the Native Realm to come up
  wait_for:
    timeout: "{{ es_api_sleep }}"
  when: manage_native_realm | bool

#perform security actions here now elasticsearch is started
- name: include xpack/security/elasticsearch-security-native.yml
  include: ./xpack/security/elasticsearch-security-native.yml
  when: manage_native_realm | bool
  run_once: True
