---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Set the URL scheme to https if SSL/TLS is enabled
  set_fact:
    es_scheme: "https"
  when: es_enable_http_ssl

- name: Fail when ssl enabled without defining a key and certificate
  fail: msg="Enabling SSL/TLS (es_enable_http_ssl or es_enable_transport_ssl) requires es_ssl_keystore and es_ssl_truststore or es_ssl_key and es_ssl_certificate to be provided"
  when:
    - es_enable_http_ssl or es_enable_transport_ssl
    - (es_ssl_key == "" or es_ssl_certificate == "")
    - (es_ssl_keystore == "" or es_ssl_truststore == "")

- name: Install Elasticsearch.
  package:
    name: "{{ es_package }}"
    state: "{{ es_package_state }}"

- name: include elasticsearch-config.yml
  include: elasticsearch-config.yml

- name: include elasticsearch-security.yml
  include: elasticsearch-security.yml

- name: include elasticsearch-ssl.yml
  include: elasticsearch-ssl.yml
  when: es_enable_http_ssl or es_enable_transport_ssl

- name: Flush handlers before Elasticsearch starts
  meta: flush_handlers

- name: Start Elasticsearch
  systemd:
    name: elasticsearch
    state: "{{ es_service_state }}"
    enabled: "{{ es_service_enabled }}"

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ es_network_host }}"
    port: "{{ es_http_port }}"
    delay: 3
    timeout: 300

# https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-users.html#set-built-in-user-passwords
- name: Set passwords for default users
  # such as: elastic, kibana, kibana_system, logstash_system, beats_system, apm_system, and remote_monitoring_user
  # You only need to create passwords for the built-in users one time for the entire cluster
  # It's minimal security configuration
  uri:
    url: "{{ es_uri }}/_security/user/{{ item.name }}/_password"
    method: POST
    body_format: json
    body: '{"password":"{{ item.password }}"}'
    status_code: 200
    user: elastic
    password: "{{ es_elastic_password }}"
    force_basic_auth: yes
    validate_certs: "{{ es_validate_certs }}"
  no_log: True
  # this task should be run once for a whole cluster
  loop:
    # https://www.elastic.co/guide/en/elasticsearch/reference/7.7/built-in-users.html
    - { name: kibana_system,          password: "{{ es_kibana_system_password | default([]) }}" }
    - { name: logstash_system,        password: "{{ es_logstash_system_password | default([]) }}" }
    - { name: beats_system,           password: "{{ es_beats_system_password | default([]) }}" }
    - { name: apm_system,             password: "{{ es_apm_system_password | default([]) }}" }
    - { name: remote_monitoring_user, password: "{{ es_remote_monitoring_user_password | default([]) }}" }
  when: item.password
