---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
  roles:
    - role: geerlingguy.java
    - role: cloud_labs.elasticsearch_cluster
      vars:
        es_enable_http_ssl: true
        es_enable_transport_ssl: false
        es_validate_certs: false
        es_elastic_password: elastic_password
        es_kibana_system_password: kibana_system_password
        es_logstash_system_password: logstash_system_password
        es_beats_system_password: beats_system_password
        es_apm_system_password: apm_system_password
        es_remote_monitoring_user_password: remote_monitoring_user_password
